main: com.ludovic.Main
name: PathfinderRPG
version: 1.0
author: Ludovic Merel
commands:
  roll:
    description: Run a dice and get the value
  hroll:
    description: Run a hidden dice and get the value
  reloadConfig:
    description: Reload the config file
  init:
    description: Set the init player
  life:
    description: Set the life player
  setColor:
    description: Set the color player